### ISSUE TITLE
App doesn't launch: Provisioning Electron Failed

### ISSUE THREAD

**Issue by Saroufim** [flathub/org.nanuc.Axolotl#1]
The app simply doesn't launch. Here's the output
```
INFO[0000] [axolotl] Starting Signal for Ubuntu version 0.9.8 
INFO[0000] [axolotl] Setup completed                    
INFO[0000] [axolotl] Start electron                     
INFO[0000] astikit: starting worker...                  
INFO[0000] [axolotl] Axolotl server started             
INFO[0000] [axolotl] Starting axolotl ws                
DEBU[0000] [axolotl] Using axolotl-web path /app/bin/axolotl-web/dist 
DEBU[0000] [axolotl] Run Backend                        
DEBU[0000] [axolotl] openDb: /home/user/.local/share/textsecure.nanuc/db 
DEBU[0000] [axolotl] NewDataStore                       
DEBU[0000] [axolotl] NewDataStore finished              
DEBU[0000] [axolotl-electron] main: starting astilectron failed: provisioning failed: provisioning electron failed: unzipping /home/user/.config/textsecure.nanuc/electron/vendor/electron-linux-amd64-v11.1.1.zip into /home/user/.config/textsecure.nanuc/electron/vendor/electron-linux-amd64 failed: unzipping /home/user/.config/textsecure.nanuc/electron/vendor/electron-linux-amd64-v11.1.1.zip into /home/user/.config/textsecure.nanuc/electron/vendor/electron-linux-amd64 failed: astikit: opening overall zip reader on /home/user/.config/textsecure.nanuc/electron/vendor/electron-linux-amd64-v11.1.1.zip failed: zip: not a valid zip file 
INFO[0000] astikit: stopping worker...                  
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x798935]

goroutine 8 [running]:
github.com/asticode/go-astilectron.(*writer).write(0x0, 0xcc3a03, 0x11, 0xcd3091, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/run/build/axolotl/src/github.com/asticode/go-astilectron/writer.go:39 +0x255
github.com/asticode/go-astilectron.synchronousEvent.func1(0xc0003c11c0, 0xcccf0c)
	/run/build/axolotl/src/github.com/asticode/go-astilectron/helper.go:145 +0xb8
github.com/asticode/go-astilectron.synchronousFunc(0xe32a78, 0xc0003c1200, 0xe262c0, 0xc000362320, 0xc0001e5518, 0xcccf0c, 0x1c, 0xc000431560, 0x79a0a0, 0xcbc774, ...)
	/run/build/axolotl/src/github.com/asticode/go-astilectron/helper.go:133 +0x208
github.com/asticode/go-astilectron.synchronousEvent(0xe32a78, 0xc0003c1200, 0xe262c0, 0xc000362320, 0x0, 0xcc3a03, 0x11, 0xcd3091, 0x1, 0x0, ...)
	/run/build/axolotl/src/github.com/asticode/go-astilectron/helper.go:144 +0x135
github.com/asticode/go-astilectron.(*Window).Create(0xc000362320, 0xcd3091, 0x1)
	/run/build/axolotl/src/github.com/asticode/go-astilectron/window.go:309 +0x1b3
main.runElectron()
	/run/build/axolotl/src/github.com/nanu-c/axolotl/main.go:126 +0x61a
main.runUI(0x0, 0x0)
	/run/build/axolotl/src/github.com/nanu-c/axolotl/main.go:58 +0x8a
created by main.main
	/run/build/axolotl/src/github.com/nanu-c/axolotl/main.go:155 +0xea
```

**Comment by olof-nord** [comment]
Hello @Saroufim, thanks for letting us know about your issue.

The issue comes from the initial download of the Electron binary, for which we use [go-astilectron](https://github.com/asticode/go-astilectron).

First, could you try to manually remove the electron binary with `rm -f /home/user/.config/textsecure.nanuc/electron/vendor/electron-linux-amd64-v11.1.1.zip` and then start axolotl again? Perhaps the zip file got corrupted during the download.

And if that doesn't do the trick, it might be worth it to uninstall axolotl and reinstall again.

Could you also let us know some more details about your system? Operating system, arch and Flatpak version for example. Just as to understand the whole picture better.

**Comment by Saroufim** [comment]
This solved the previous error but yielded other ones:
```
INFO[0000] [axolotl] Starting Signal for Ubuntu version 0.9.8 
INFO[0000] [axolotl] Setup completed                    
INFO[0000] [axolotl] Start electron                     
DEBU[0000] [axolotl] Run Backend                        
INFO[0000] astikit: starting worker...                  
DEBU[0000] [axolotl] openDb: /home/user/.local/share/textsecure.nanuc/db 
DEBU[0000] [axolotl] NewDataStore                       
INFO[0000] [axolotl] Axolotl server started             
INFO[0000] [axolotl] Starting axolotl ws                
DEBU[0000] [axolotl] Using axolotl-web path /app/bin/axolotl-web/dist 
DEBU[0000] [axolotl] NewDataStore finished              
INFO[0000] [axolotl] Loading Chats                      
INFO[0000] [axolotl] Db setup finished                  
DEBU[0000] [axolotl] Start Session after Decryption     
DEBU[0000] [axolotl] starting Signal connection         
DEBU[0000] [axolotl] config path:  /home/user/.config/textsecure.nanuc 
DEBU[2021/03/21 22:17:27] [axoltol] Opening Dialog: getPhoneNumber     
DEBU[2021/03/21 22:17:27] [axolotl-ws] send request getPhoneNumber     
ERRO[0020] '/home/user/.config/textsecure.nanuc/electron/vendor/electron-linux-amd64/electron' exited with code: -1 
INFO[0020] astikit: stopping worker...                  
DEBU[2021/03/21 22:17:47] [axolotl-electron] main: creating window failed: context canceled 
DEBU[2021/03/21 22:17:47] [axolotl-electron] open dev tools false      
INFO[0020] astikit: worker is now waiting...            
ERRO[0020] accept tcp 127.0.0.1:46273: use of closed network connection while TCP accepting 
```
OS: Fedora Silverblue 34 Arch: x86 Flatpak: 1.10.1

**Comment by olof-nord** [comment]
Well, one problem less!

The "use of closed network connection while TCP accepting"  is a current issue, for which we are still investigating.

https://github.com/nanu-c/axolotl/issues/433

There is a second Flatpak packaging, using QT instead of Electron, for which some have a better result: see https://github.com/nanu-c/axolotl/blob/main/docs/INSTALL.md#qt-version for a step-by-step guide.

**Comment by olof-nord** [comment]
Hello @Saroufim, the previous version of Axolotl tried to download Electron during startup, something which caused many different problems. The recently released version (1.1.0) instead comes with a bundled Electron and during testing provides much more reliable results.

Once the production build is through, try to update and let us know how it went?

**Comment by Saroufim** [comment]
Hello. The main UI now launches. After entering my phone number, I get asked to fill a captcha which does nothing upon completion and then expires after 3-4 minutes. Solving it again doesn't do anything either. There is nothing interesting in the command line. The last like would be "received pong response from websocket" and nothing gets logged after that.

**Comment by nanu-c** [comment]
It's this problem, they switched to recaptcha enterprise and now it's more difficult. https://github.com/nanu-c/axolotl/issues/771

**Comment by nanu-c** [comment]
This is the workaround, but it hasn't been tested well.
https://github.com/nanu-c/axolotl/pull/775

**Comment by olof-nord** [comment]
Just to follow up on this one: with the latest release of Axolotl, the mentioned recaptcha issue is included. Did it solve your problem @Saroufim?

**Comment by Saroufim** [comment]
Yes it did

**Comment by olof-nord** [comment]
Happy to hear! Closing this issue then :+1:
